<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graph"
    nsURI="graph" nsPrefix="graph">
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//IdentifiableElement">
    <eOperations name="clone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        unsettable="true" eOpposite="#//Graph/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//Layer" eOpposite="#//Layer/nodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelableElement">
    <eOperations name="addLabel">
      <eParameters name="label" eType="#//Label"/>
    </eOperations>
    <eOperations name="getLabel" eType="#//Label">
      <eParameters name="ns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLabel" eType="#//Label">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getNumOfLabels" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="getLabelsByNamespace" upperBound="-1" eType="#//Label">
      <eParameters name="ns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="hasLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="differences" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="obj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="#//Label" containment="true" eOpposite="#//Label/labelableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        eOpposite="#//Graph/edges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//Layer" eOpposite="#//Layer/edges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentifiableElement" eSuperTypes="#//LabelableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" lowerBound="1"
        eType="#//Identifier" volatile="true" transient="true" eOpposite="#//Identifier/identifiableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//LabelableElement">
    <eOperations name="getNSSeperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="clone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelableElement" eType="#//LabelableElement"
        eOpposite="#//LabelableElement/labels"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//IdentifiableElement">
    <eOperations name="addNode">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="getNode" eType="#//Node">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeNode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="removeNodeById" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addEdge">
      <eParameters name="edge" eType="#//Edge"/>
    </eOperations>
    <eOperations name="getEdge" eType="#//Edge">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="nodeId2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getInEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getOutEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeEdgeById" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeEdges" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="removeNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="removeEdge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="edge" eType="#//Edge"/>
    </eOperations>
    <eOperations name="changeEdgeSource">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="changeEdgeTarget">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addNode">
      <eParameters name="node" eType="#//Node"/>
      <eParameters name="layer" eType="#//Layer"/>
    </eOperations>
    <eOperations name="addEdge">
      <eParameters name="edge" eType="#//Edge"/>
      <eParameters name="layer" eType="#//Layer"/>
    </eOperations>
    <eOperations name="addLayer">
      <eParameters name="layer" eType="#//Layer"/>
    </eOperations>
    <eOperations name="getLayer" eType="#//Layer">
      <eParameters name="layerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getRoots" upperBound="-1" eType="#//Node"/>
    <eOperations name="getLeafs" upperBound="-1" eType="#//Node"/>
    <eOperations name="traverse">
      <eParameters name="startNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="traverseType" eType="#//GRAPH_TRAVERSE_TYPE"/>
      <eParameters name="traverseId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="traverseHandler" eType="#//GraphTraverseHandler"/>
    </eOperations>
    <eOperations name="traverse">
      <eParameters name="startNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="traverseType" eType="#//GRAPH_TRAVERSE_TYPE"/>
      <eParameters name="traverseId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="traverseHandler" eType="#//GraphTraverseHandler"/>
      <eParameters name="isCycleSafe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexMgr" eType="#//index/IndexMgr"
        volatile="true" transient="true" eOpposite="#//index/IndexMgr/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true" eOpposite="#//Edge/graph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfEdges" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//Layer" containment="true" eOpposite="#//Layer/graph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfLayers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier" eSuperTypes="#//Label">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifiableElement" eType="#//IdentifiableElement"
        volatile="true" transient="true" eOpposite="#//IdentifiableElement/identifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layer" eSuperTypes="#//IdentifiableElement">
    <eOperations name="getAllSubLayers" upperBound="-1" eType="#//Layer"/>
    <eOperations name="getAllIncludedNodes" upperBound="-1" eType="#//Node"/>
    <eOperations name="getAllIncludedEdges" upperBound="-1" eType="#//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        eOpposite="#//Graph/layers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" eOpposite="#//Node/layers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/layers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superLayer" eType="#//Layer"
        eOpposite="#//Layer/subLayers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subLayers" upperBound="-1"
        eType="#//Layer" eOpposite="#//Layer/superLayer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="GraphTraverseHandler" instanceClassName="de.hu_berlin.german.korpling.saltnpepper.salt.graph.GraphTraverseHandler"/>
  <eClassifiers xsi:type="ecore:EEnum" name="GRAPH_TRAVERSE_TYPE">
    <eLiterals name="TOP_DOWN_DEPTH_FIRST"/>
    <eLiterals name="TOP_DOWN_BREADTH_FIRST" value="1"/>
    <eLiterals name="BOTTOM_UP_DEPTH_FIRST" value="2"/>
    <eLiterals name="BOTTOM_UP_BREADTH_FIRST" value="3"/>
  </eClassifiers>
  <eSubpackages name="index" nsURI="index" nsPrefix="index">
    <eClassifiers xsi:type="ecore:EClass" name="Index" abstract="true" interface="true"
        eSuperTypes="#//IdentifiableElement">
      <eOperations name="addElement">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        <eParameters name="element" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="hasElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="removeElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="element" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfElements" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          changeable="false" volatile="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleIndex" eSuperTypes="#//index/Index">
      <eOperations name="getElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="removeElementById" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idxTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"
          changeable="false" volatile="true" transient="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndexMgr">
      <eOperations name="addIndex">
        <eParameters name="index" eType="#//index/Index"/>
      </eOperations>
      <eOperations name="hasIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="getIndex" eType="#//index/Index">
        <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="removeIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eOperations name="removeElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
          eType="#//index/Index" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfIndexes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
          volatile="true" transient="true" eOpposite="#//Graph/indexMgr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexIndex" eSuperTypes="#//index/Index">
      <eOperations name="hasSlot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="getSlot" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="getSlotIds" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      <eOperations name="removeSlot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfSlots" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idxTable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap"
          volatile="true" transient="true"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
