<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graph" nsURI="graph" nsPrefix="graph">
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//IdentifiableElement">
    <eOperations name="clone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        unsettable="true" eOpposite="#//Graph/nodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//Layer" eOpposite="#//Layer/nodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabelableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="@export java.io.Serializable"/>
    </eAnnotations>
    <eOperations name="addLabel">
      <eParameters name="label" eType="#//Label"/>
    </eOperations>
    <eOperations name="getLabel" eType="#//Label">
      <eParameters name="ns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getLabel" eType="#//Label">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getNumOfLabels" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="getLabelsByNamespace" upperBound="-1" eType="#//Label">
      <eParameters name="ns" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="hasLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeLabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="differences" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="obj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labels" upperBound="-1"
        eType="#//Label" containment="true" eOpposite="#//Label/labelableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" eSuperTypes="#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        eOpposite="#//Graph/edges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//Layer" eOpposite="#//Layer/edges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdentifiableElement" eSuperTypes="#//LabelableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifier" lowerBound="1"
        eType="#//Identifier" volatile="true" transient="true" eOpposite="#//Identifier/identifiableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" eSuperTypes="#//LabelableElement">
    <eOperations name="getNSSeperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eOperations name="clone" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labelableElement" eType="#//LabelableElement"
        eOpposite="#//LabelableElement/labels"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Graph" eSuperTypes="#//IdentifiableElement">
    <eOperations name="addNode">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="getNode" eType="#//Node">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeNode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="node" eType="#//Node"/>
    </eOperations>
    <eOperations name="removeNodeById" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addEdge">
      <eParameters name="edge" eType="#//Edge"/>
    </eOperations>
    <eOperations name="getEdge" eType="#//Edge">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="nodeId2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getInEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getOutEdges" upperBound="-1" eType="#//Edge">
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeEdgeById" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="removeEdges" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="removeNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eOperations name="removeEdge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
      <eParameters name="edge" eType="#//Edge"/>
    </eOperations>
    <eOperations name="changeEdgeSource">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="changeEdgeTarget">
      <eParameters name="edgeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="nodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addNode">
      <eParameters name="node" eType="#//Node"/>
      <eParameters name="layer" eType="#//Layer"/>
    </eOperations>
    <eOperations name="addEdge">
      <eParameters name="edge" eType="#//Edge"/>
      <eParameters name="layer" eType="#//Layer"/>
    </eOperations>
    <eOperations name="addLayer">
      <eParameters name="layer" eType="#//Layer"/>
    </eOperations>
    <eOperations name="getLayer" eType="#//Layer">
      <eParameters name="layerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getRoots" upperBound="-1" eType="#//Node"/>
    <eOperations name="getLeafs" upperBound="-1" eType="#//Node"/>
    <eOperations name="traverse">
      <eParameters name="startNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="traverseType" eType="#//GRAPH_TRAVERSE_TYPE"/>
      <eParameters name="traverseId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="traverseHandler" eType="#//GraphTraverseHandler"/>
    </eOperations>
    <eOperations name="traverse">
      <eParameters name="startNodes" upperBound="-1" eType="#//Node"/>
      <eParameters name="traverseType" eType="#//GRAPH_TRAVERSE_TYPE"/>
      <eParameters name="traverseId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="traverseHandler" eType="#//GraphTraverseHandler"/>
      <eParameters name="isCycleSafe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="indexMgr" eType="#//index/IndexMgr"
        volatile="true" transient="true" eOpposite="#//index/IndexMgr/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true" eOpposite="#//Node/graph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true" eOpposite="#//Edge/graph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfNodes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfEdges" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layers" upperBound="-1"
        eType="#//Layer" containment="true" eOpposite="#//Layer/graph"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfLayers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Identifier" eSuperTypes="#//Label">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifiableElement" eType="#//IdentifiableElement"
        volatile="true" transient="true" eOpposite="#//IdentifiableElement/identifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Layer" eSuperTypes="#//IdentifiableElement">
    <eOperations name="getAllSubLayers" upperBound="-1" eType="#//Layer"/>
    <eOperations name="getAllIncludedNodes" upperBound="-1" eType="#//Node"/>
    <eOperations name="getAllIncludedEdges" upperBound="-1" eType="#//Edge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
        eOpposite="#//Graph/layers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" eOpposite="#//Node/layers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/layers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superLayer" eType="#//Layer"
        eOpposite="#//Layer/subLayers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subLayers" upperBound="-1"
        eType="#//Layer" eOpposite="#//Layer/superLayer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="GraphTraverseHandler" instanceClassName="de.hu_berlin.german.korpling.saltnpepper.salt.graph.GraphTraverseHandler"/>
  <eClassifiers xsi:type="ecore:EEnum" name="GRAPH_TRAVERSE_TYPE">
    <eLiterals name="TOP_DOWN_DEPTH_FIRST"/>
    <eLiterals name="TOP_DOWN_BREADTH_FIRST" value="1"/>
    <eLiterals name="BOTTOM_UP_DEPTH_FIRST" value="2"/>
    <eLiterals name="BOTTOM_UP_BREADTH_FIRST" value="3"/>
  </eClassifiers>
  <eSubpackages name="index" nsURI="index" nsPrefix="index">
    <eClassifiers xsi:type="ecore:EClass" name="Index" abstract="true" interface="true"
        eSuperTypes="#//IdentifiableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A class implementing this interface provides an index for a faster access on indexed objects. An {@link Index} object indexes a single object (so called value or element) or a set of objects (so called values or elements) by using a unique key (also called elementId) for indexing them. In case of the {@link Index} object is of type  {@link SimpleIndex}, each key has exactly one value in case of the {@link Index} object is of type {@link ComplexIndex}, each key has a list of values."/>
      </eAnnotations>
      <eTypeParameters name="K"/>
      <eTypeParameters name="V"/>
      <eOperations name="addElement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method adds an element to slot with given id. If no slot exists it will be created. No element will ever be inserted into the same slot more than once.&#xD;&#xA;@param id Object - identifier for slot&#xD;&#xA;@param element Object - adding element  "/>
        </eAnnotations>
        <eParameters name="elementId">
          <eGenericType eTypeParameter="#//index/Index/K"/>
        </eParameters>
        <eParameters name="element">
          <eGenericType eTypeParameter="#//index/Index/V"/>
        </eParameters>
      </eOperations>
      <eOperations name="hasElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId">
          <eGenericType eTypeParameter="#//index/Index/K"/>
        </eParameters>
      </eOperations>
      <eOperations name="removeElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Removes the given element from this index.&#xD;&#xA;@param element - the element which shall be removed&#xD;&#xA;@return true, if removing was successful "/>
        </eAnnotations>
        <eParameters name="element">
          <eGenericType eTypeParameter="#//index/Index/V"/>
        </eParameters>
      </eOperations>
      <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfElements" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfElementIds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexMap" volatile="true"
          transient="true">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eTypeParameter="#//index/Index/K"/>
          <eTypeArguments eTypeParameter="#//index/Index/V"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="estimatedCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          defaultValueLiteral="10000">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Determines the estimated size of this index. For instance this value can be used by implemnting calsses as inital cpacity for e.g. {@link HashMap} objects etc.. The default value is set to {@value #ESTIMATED_CAPACITY_EDEFAULT}. A reset currently is ineffective."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SimpleIndex">
      <eTypeParameters name="K"/>
      <eTypeParameters name="V"/>
      <eOperations name="getElement">
        <eGenericType eTypeParameter="#//index/SimpleIndex/V"/>
        <eParameters name="elementId">
          <eGenericType eTypeParameter="#//index/SimpleIndex/K"/>
        </eParameters>
      </eOperations>
      <eOperations name="removeElementById" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId">
          <eGenericType eTypeParameter="#//index/SimpleIndex/K"/>
        </eParameters>
      </eOperations>
      <eGenericSuperTypes eClassifier="#//index/Index">
        <eTypeArguments eTypeParameter="#//index/SimpleIndex/K"/>
        <eTypeArguments eTypeParameter="#//index/SimpleIndex/V"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndexMgr">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This class manages a set of Index objects, for faster access on {@link Graph} members. Such an {@link Index} object indexes a single object (so called value) or a set of objects (so called values) by using a unique key for indexing them. In case of the {@link Index} object is of type  {@link SimpleIndex}, each key has exactly one value in case of the {@link Index} object is of type {@link ComplexIndex}, each key has a list of values."/>
      </eAnnotations>
      <eOperations name="addIndex">
        <eParameters name="index" eType="#//index/Index"/>
      </eOperations>
      <eOperations name="hasIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="getIndex" eType="#//index/Index">
        <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="removeIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="indexId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eOperations name="removeAll" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eOperations name="removeElement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="indexes" upperBound="-1"
          eType="#//index/Index" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numOfIndexes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELongObject"
          changeable="false" volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="graph" eType="#//Graph"
          volatile="true" transient="true" eOpposite="#//Graph/indexMgr"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexIndex">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A {@link ComplexIndex} object refers a key (or elementId) to a set of values (or elements). Such a set is stored in a {@link EList} object."/>
      </eAnnotations>
      <eTypeParameters name="K"/>
      <eTypeParameters name="V"/>
      <eOperations name="hasSlot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns if index has a slot with the given id.&#xD;&#xA;@param id Object - identifier for slot&#xD;&#xA;@return true, if there exists a slot with given id"/>
        </eAnnotations>
        <eParameters name="elementId">
          <eGenericType eTypeParameter="#//index/ComplexIndex/K"/>
        </eParameters>
      </eOperations>
      <eOperations name="getSlot" upperBound="-1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This method returns a slot matching to the given id. If id does not exist in index returned list is empty.&#xD;&#xA;@return matching slot"/>
        </eAnnotations>
        <eGenericType eTypeParameter="#//index/ComplexIndex/V"/>
        <eParameters name="elementId">
          <eGenericType eTypeParameter="#//index/ComplexIndex/K"/>
        </eParameters>
      </eOperations>
      <eOperations name="getSlotIds" upperBound="-1">
        <eGenericType eTypeParameter="#//index/ComplexIndex/K"/>
      </eOperations>
      <eOperations name="removeSlot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject">
        <eParameters name="elementId">
          <eGenericType eTypeParameter="#//index/ComplexIndex/K"/>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sortable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          changeable="false" defaultValueLiteral="false"/>
      <eGenericSuperTypes eClassifier="#//index/Index">
        <eTypeArguments eTypeParameter="#//index/ComplexIndex/K"/>
        <eTypeArguments eTypeParameter="#//index/ComplexIndex/V"/>
      </eGenericSuperTypes>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
