var searchData=
[
  ['sabstractannotation',['SAbstractAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_abstract_annotation.html',1,'org::corpus_tools::salt::core']]],
  ['sabstractannotationimpl',['SAbstractAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_abstract_annotation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['salt_5ftype',['SALT_TYPE',['../enumorg_1_1corpus__tools_1_1salt_1_1_s_a_l_t___t_y_p_e.html',1,'org::corpus_tools::salt']]],
  ['saltelementnotingraphexception',['SaltElementNotInGraphException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_element_not_in_graph_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['saltexception',['SaltException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['saltfactory',['SaltFactory',['../classorg_1_1corpus__tools_1_1salt_1_1_salt_factory.html',1,'org::corpus_tools::salt']]],
  ['saltfactoryimpl',['SaltFactoryImpl',['../classorg_1_1corpus__tools_1_1salt_1_1impl_1_1_salt_factory_impl.html',1,'org::corpus_tools::salt::impl']]],
  ['saltinsertionexception',['SaltInsertionException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_insertion_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['saltinvalidmodelexception',['SaltInvalidModelException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_invalid_model_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['saltnotificationfactory',['SaltNotificationFactory',['../classorg_1_1corpus__tools_1_1salt_1_1extensions_1_1notification_1_1_salt_notification_factory.html',1,'org::corpus_tools::salt::extensions::notification']]],
  ['saltparameterexception',['SaltParameterException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_parameter_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['saltproject',['SaltProject',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_salt_project.html',1,'org::corpus_tools::salt::common']]],
  ['saltprojectimpl',['SaltProjectImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_salt_project_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['saltresourceexception',['SaltResourceException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_resource_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['saltsampleexception',['SaltSampleException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_sample_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['salttokenizerexception',['SaltTokenizerException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_tokenizer_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['salttraverserexception',['SaltTraverserException',['../classorg_1_1corpus__tools_1_1salt_1_1exceptions_1_1_salt_traverser_exception.html',1,'org::corpus_tools::salt::exceptions']]],
  ['saltutil',['SaltUtil',['../classorg_1_1corpus__tools_1_1salt_1_1util_1_1_salt_util.html',1,'org::corpus_tools::salt::util']]],
  ['saltxml10dictionary',['SaltXML10Dictionary',['../interfaceorg_1_1corpus__tools_1_1salt_1_1util_1_1internal_1_1persistence_1_1_salt_x_m_l10_dictionary.html',1,'org::corpus_tools::salt::util::internal::persistence']]],
  ['saltxml10handler',['SaltXML10Handler',['../classorg_1_1corpus__tools_1_1salt_1_1util_1_1internal_1_1persistence_1_1_salt_x_m_l10_handler.html',1,'org::corpus_tools::salt::util::internal::persistence']]],
  ['saltxml10writer',['SaltXML10Writer',['../classorg_1_1corpus__tools_1_1salt_1_1util_1_1internal_1_1persistence_1_1_salt_x_m_l10_writer.html',1,'org::corpus_tools::salt::util::internal::persistence']]],
  ['samplegenerator',['SampleGenerator',['../classorg_1_1corpus__tools_1_1salt_1_1samples_1_1_sample_generator.html',1,'org::corpus_tools::salt::samples']]],
  ['sannotation',['SAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_annotation.html',1,'org::corpus_tools::salt::core']]],
  ['sannotationcontainer',['SAnnotationContainer',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_annotation_container.html',1,'org::corpus_tools::salt::core']]],
  ['sannotationcontainerhelper',['SAnnotationContainerHelper',['../classorg_1_1corpus__tools_1_1salt_1_1util_1_1internal_1_1_s_annotation_container_helper.html',1,'org::corpus_tools::salt::util::internal']]],
  ['sannotationimpl',['SAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_annotation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['scatannotation',['SCatAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1semantics_1_1_s_cat_annotation.html',1,'org::corpus_tools::salt::semantics']]],
  ['scatannotationimpl',['SCatAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1semantics_1_1impl_1_1_s_cat_annotation_impl.html',1,'org::corpus_tools::salt::semantics::impl']]],
  ['scorpus',['SCorpus',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_corpus.html',1,'org::corpus_tools::salt::common']]],
  ['scorpusdocumentrelation',['SCorpusDocumentRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_corpus_document_relation.html',1,'org::corpus_tools::salt::common']]],
  ['scorpusdocumentrelationimpl',['SCorpusDocumentRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_corpus_document_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['scorpusgraph',['SCorpusGraph',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_corpus_graph.html',1,'org::corpus_tools::salt::common']]],
  ['scorpusgraphdotwriter',['SCorpusGraphDOTWriter',['../classorg_1_1corpus__tools_1_1salt_1_1util_1_1internal_1_1persistence_1_1dot_1_1_s_corpus_graph_d_o_t_writer.html',1,'org::corpus_tools::salt::util::internal::persistence::dot']]],
  ['scorpusgraphimpl',['SCorpusGraphImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_corpus_graph_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['scorpusimpl',['SCorpusImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_corpus_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['scorpusrelation',['SCorpusRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_corpus_relation.html',1,'org::corpus_tools::salt::common']]],
  ['scorpusrelationimpl',['SCorpusRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_corpus_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['sdatatype',['SDATATYPE',['../namespaceorg_1_1corpus__tools_1_1salt.html#enumorg_1_1corpus__tools_1_1salt_1_1_s_d_a_t_a_t_y_p_e',1,'org::corpus_tools::salt']]],
  ['sdocument',['SDocument',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_document.html',1,'org::corpus_tools::salt::common']]],
  ['sdocumentgraph',['SDocumentGraph',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_document_graph.html',1,'org::corpus_tools::salt::common']]],
  ['sdocumentgraphdotwriter',['SDocumentGraphDOTWriter',['../classorg_1_1corpus__tools_1_1salt_1_1util_1_1internal_1_1persistence_1_1dot_1_1_s_document_graph_d_o_t_writer.html',1,'org::corpus_tools::salt::util::internal::persistence::dot']]],
  ['sdocumentgraphimpl',['SDocumentGraphImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_document_graph_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['sdocumentgraphobject',['SDocumentGraphObject',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_document_graph_object.html',1,'org::corpus_tools::salt::common']]],
  ['sdocumentimpl',['SDocumentImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_document_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['sdominancerelation',['SDominanceRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_dominance_relation.html',1,'org::corpus_tools::salt::common']]],
  ['sdominancerelationimpl',['SDominanceRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_dominance_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['sfeature',['SFeature',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_feature.html',1,'org::corpus_tools::salt::core']]],
  ['sfeatureimpl',['SFeatureImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_feature_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['sgraph',['SGraph',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_graph.html',1,'org::corpus_tools::salt::core']]],
  ['sgraphimpl',['SGraphImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_graph_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['simpletokenizer',['SimpleTokenizer',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1tokenizer_1_1_simple_tokenizer.html',1,'org::corpus_tools::salt::common::tokenizer']]],
  ['slayer',['SLayer',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_layer.html',1,'org::corpus_tools::salt::core']]],
  ['slayerimpl',['SLayerImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_layer_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['slemmaannotation',['SLemmaAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1semantics_1_1_s_lemma_annotation.html',1,'org::corpus_tools::salt::semantics']]],
  ['slemmaannotationimpl',['SLemmaAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1semantics_1_1impl_1_1_s_lemma_annotation_impl.html',1,'org::corpus_tools::salt::semantics::impl']]],
  ['smedialds',['SMedialDS',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_medial_d_s.html',1,'org::corpus_tools::salt::common']]],
  ['smedialdsimpl',['SMedialDSImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_medial_d_s_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['smedialrelation',['SMedialRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_medial_relation.html',1,'org::corpus_tools::salt::common']]],
  ['smedialrelationimpl',['SMedialRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_medial_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['smetaannotation',['SMetaAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_meta_annotation.html',1,'org::corpus_tools::salt::core']]],
  ['smetaannotationimpl',['SMetaAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_meta_annotation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['snamedelement',['SNamedElement',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_named_element.html',1,'org::corpus_tools::salt::core']]],
  ['snode',['SNode',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_node.html',1,'org::corpus_tools::salt::core']]],
  ['snodeimpl',['SNodeImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_node_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['sorderrelation',['SOrderRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_order_relation.html',1,'org::corpus_tools::salt::common']]],
  ['sorderrelationimpl',['SOrderRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_order_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['spathelement',['SPathElement',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_path_element.html',1,'org::corpus_tools::salt::core']]],
  ['spointingrelation',['SPointingRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_pointing_relation.html',1,'org::corpus_tools::salt::common']]],
  ['spointingrelationimpl',['SPointingRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_pointing_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['sposannotation',['SPOSAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1semantics_1_1_s_p_o_s_annotation.html',1,'org::corpus_tools::salt::semantics']]],
  ['sposannotationimpl',['SPOSAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1semantics_1_1impl_1_1_s_p_o_s_annotation_impl.html',1,'org::corpus_tools::salt::semantics::impl']]],
  ['sprocessingannotation',['SProcessingAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_processing_annotation.html',1,'org::corpus_tools::salt::core']]],
  ['sprocessingannotationimpl',['SProcessingAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_processing_annotation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['srelation',['SRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_relation.html',1,'org::corpus_tools::salt::core']]],
  ['srelation_3c_20org_3a_3acorpus_5ftools_3a_3asalt_3a_3acore_3a_3asnode_2c_20org_3a_3acorpus_5ftools_3a_3asalt_3a_3acore_3a_3asnode_20_3e',['SRelation&lt; org::corpus_tools::salt::core::SNode, org::corpus_tools::salt::core::SNode &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_relation.html',1,'org::corpus_tools::salt::core']]],
  ['srelation_3c_20s_2c_20t_20_3e',['SRelation&lt; S, T &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_relation.html',1,'org::corpus_tools::salt::core']]],
  ['srelation_3c_20scorpus_2c_20scorpus_20_3e',['SRelation&lt; SCorpus, SCorpus &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_relation.html',1,'org::corpus_tools::salt::core']]],
  ['srelation_3c_20scorpus_2c_20sdocument_20_3e',['SRelation&lt; SCorpus, SDocument &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_relation.html',1,'org::corpus_tools::salt::core']]],
  ['srelation_3c_20sspan_2c_20stoken_20_3e',['SRelation&lt; SSpan, SToken &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_relation.html',1,'org::corpus_tools::salt::core']]],
  ['srelation_3c_20sstructurednode_2c_20sstructurednode_20_3e',['SRelation&lt; SStructuredNode, SStructuredNode &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_relation.html',1,'org::corpus_tools::salt::core']]],
  ['srelationimpl',['SRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_relation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['srelationimpl_3c_20s_2c_20t_20_3e',['SRelationImpl&lt; S, T &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_relation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['srelationimpl_3c_20scorpus_2c_20scorpus_20_3e',['SRelationImpl&lt; SCorpus, SCorpus &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_relation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['srelationimpl_3c_20scorpus_2c_20sdocument_20_3e',['SRelationImpl&lt; SCorpus, SDocument &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_relation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['srelationimpl_3c_20sspan_2c_20stoken_20_3e',['SRelationImpl&lt; SSpan, SToken &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_relation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['srelationimpl_3c_20sstructure_2c_20sstructurednode_20_3e',['SRelationImpl&lt; SStructure, SStructuredNode &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_relation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['srelationimpl_3c_20sstructurednode_2c_20sstructurednode_20_3e',['SRelationImpl&lt; SStructuredNode, SStructuredNode &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1core_1_1impl_1_1_s_relation_impl.html',1,'org::corpus_tools::salt::core::impl']]],
  ['ssentenceannotation',['SSentenceAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1semantics_1_1_s_sentence_annotation.html',1,'org::corpus_tools::salt::semantics']]],
  ['ssentenceannotationimpl',['SSentenceAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1semantics_1_1impl_1_1_s_sentence_annotation_impl.html',1,'org::corpus_tools::salt::semantics::impl']]],
  ['ssequentialds',['SSequentialDS',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_d_s.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialds_3c_20d_2c_20p_20_3e',['SSequentialDS&lt; D, P &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_d_s.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialds_3c_20integer_2c_20integer_20_3e',['SSequentialDS&lt; Integer, Integer &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_d_s.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialds_3c_20string_2c_20integer_20_3e',['SSequentialDS&lt; String, Integer &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_d_s.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialds_3c_20uri_2c_20double_20_3e',['SSequentialDS&lt; URI, Double &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_d_s.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialdsimpl',['SSequentialDSImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_sequential_d_s_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['ssequentialdsimpl_3c_20integer_2c_20integer_20_3e',['SSequentialDSImpl&lt; Integer, Integer &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_sequential_d_s_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['ssequentialdsimpl_3c_20string_2c_20integer_20_3e',['SSequentialDSImpl&lt; String, Integer &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_sequential_d_s_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['ssequentialdsimpl_3c_20uri_2c_20double_20_3e',['SSequentialDSImpl&lt; URI, Double &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_sequential_d_s_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['ssequentialrelation',['SSequentialRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_relation.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialrelation_3c_20s_2c_20t_2c_20p_20_3e',['SSequentialRelation&lt; S, T, P &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_relation.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialrelation_3c_20stoken_2c_20smedialds_2c_20double_20_3e',['SSequentialRelation&lt; SToken, SMedialDS, Double &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_relation.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialrelation_3c_20stoken_2c_20stextualds_2c_20integer_20_3e',['SSequentialRelation&lt; SToken, STextualDS, Integer &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_relation.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialrelation_3c_20stoken_2c_20stimeline_2c_20integer_20_3e',['SSequentialRelation&lt; SToken, STimeline, Integer &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_sequential_relation.html',1,'org::corpus_tools::salt::common']]],
  ['ssequentialrelationimpl',['SSequentialRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_sequential_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['ssequentialrelationimpl_3c_20stoken_2c_20smedialds_2c_20double_20_3e',['SSequentialRelationImpl&lt; SToken, SMedialDS, Double &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_sequential_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['ssequentialrelationimpl_3c_20stoken_2c_20stextualds_2c_20integer_20_3e',['SSequentialRelationImpl&lt; SToken, STextualDS, Integer &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_sequential_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['ssequentialrelationimpl_3c_20stoken_2c_20stimeline_2c_20integer_20_3e',['SSequentialRelationImpl&lt; SToken, STimeline, Integer &gt;',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_sequential_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['sspan',['SSpan',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_span.html',1,'org::corpus_tools::salt::common']]],
  ['sspanimpl',['SSpanImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_span_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['sspanningrelation',['SSpanningRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_spanning_relation.html',1,'org::corpus_tools::salt::common']]],
  ['sspanningrelationimpl',['SSpanningRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_spanning_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['sstructure',['SStructure',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_structure.html',1,'org::corpus_tools::salt::common']]],
  ['sstructurednode',['SStructuredNode',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_structured_node.html',1,'org::corpus_tools::salt::common']]],
  ['sstructureimpl',['SStructureImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_structure_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['stextoverlappingrelation',['STextOverlappingRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_text_overlapping_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stextoverlappingrelation_3c_20sspan_2c_20stoken_20_3e',['STextOverlappingRelation&lt; SSpan, SToken &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_text_overlapping_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stextoverlappingrelation_3c_20sstructure_2c_20sstructurednode_20_3e',['STextOverlappingRelation&lt; SStructure, SStructuredNode &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_text_overlapping_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stextoverlappingrelation_3c_20stoken_2c_20stextualds_20_3e',['STextOverlappingRelation&lt; SToken, STextualDS &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_text_overlapping_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stextualds',['STextualDS',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_textual_d_s.html',1,'org::corpus_tools::salt::common']]],
  ['stextualdsimpl',['STextualDSImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_textual_d_s_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['stextualrelation',['STextualRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_textual_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stextualrelationimpl',['STextualRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_textual_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['stextualrelationsstartcomparator',['STextualRelationSStartComparator',['../classorg_1_1corpus__tools_1_1salt_1_1util_1_1_s_textual_relation_s_start_comparator.html',1,'org::corpus_tools::salt::util']]],
  ['stimeline',['STimeline',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_timeline.html',1,'org::corpus_tools::salt::common']]],
  ['stimelineimpl',['STimelineImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_timeline_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['stimelinerelation',['STimelineRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_timeline_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stimelinerelationimpl',['STimelineRelationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_timeline_relation_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['stimeoverlappingrelation',['STimeOverlappingRelation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_time_overlapping_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stimeoverlappingrelation_3c_20sspan_2c_20stoken_20_3e',['STimeOverlappingRelation&lt; SSpan, SToken &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_time_overlapping_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stimeoverlappingrelation_3c_20sstructure_2c_20sstructurednode_20_3e',['STimeOverlappingRelation&lt; SStructure, SStructuredNode &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_time_overlapping_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stimeoverlappingrelation_3c_20stoken_2c_20stimeline_20_3e',['STimeOverlappingRelation&lt; SToken, STimeline &gt;',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_time_overlapping_relation.html',1,'org::corpus_tools::salt::common']]],
  ['stoken',['SToken',['../interfaceorg_1_1corpus__tools_1_1salt_1_1common_1_1_s_token.html',1,'org::corpus_tools::salt::common']]],
  ['stokenimpl',['STokenImpl',['../classorg_1_1corpus__tools_1_1salt_1_1common_1_1impl_1_1_s_token_impl.html',1,'org::corpus_tools::salt::common::impl']]],
  ['stypeannotation',['STypeAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1semantics_1_1_s_type_annotation.html',1,'org::corpus_tools::salt::semantics']]],
  ['stypeannotationimpl',['STypeAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1semantics_1_1impl_1_1_s_type_annotation_impl.html',1,'org::corpus_tools::salt::semantics::impl']]],
  ['stypedelement',['STypedElement',['../interfaceorg_1_1corpus__tools_1_1salt_1_1core_1_1_s_typed_element.html',1,'org::corpus_tools::salt::core']]],
  ['swordannotation',['SWordAnnotation',['../interfaceorg_1_1corpus__tools_1_1salt_1_1semantics_1_1_s_word_annotation.html',1,'org::corpus_tools::salt::semantics']]],
  ['swordannotationimpl',['SWordAnnotationImpl',['../classorg_1_1corpus__tools_1_1salt_1_1semantics_1_1impl_1_1_s_word_annotation_impl.html',1,'org::corpus_tools::salt::semantics::impl']]]
];
