/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.salt.model.saltCore.validation;

import de.corpling.salt.model.saltCore.SAnnotatableElement;
import de.corpling.salt.model.saltCore.SElementPath;
import de.corpling.salt.model.saltCore.SGraph;
import de.corpling.salt.model.saltCore.SProcessingAnnotatableElement;
import de.corpling.salt.model.saltCore.SStereotypeableElement;

/**
 * A sample validator interface for {@link de.corpling.salt.model.saltCore.SElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SElementValidator {
	boolean validate();

	boolean validateSSterotypeableElement(SStereotypeableElement value);

	boolean validateSAnnotatableElement(SAnnotatableElement value);

	boolean validateSProcessingAnnotatableElement(SProcessingAnnotatableElement value);

	boolean validateSGraph(SGraph value);

	boolean validateSElementPath(SElementPath value);
}
