/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.salt.model.saltCore.validation;

import de.corpling.salt.model.saltCore.SELEMENT_TYPE;
import de.corpling.salt.model.saltCore.SIdentifiableElement;

/**
 * A sample validator interface for {@link de.corpling.salt.model.saltCore.SElementPath}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SElementPathValidator {
	boolean validate();

	boolean validateParentPath(String value);
	boolean validateSElement(SIdentifiableElement value);
	boolean validateName(String value);
	boolean validateElementType(SELEMENT_TYPE value);
}
