/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.salt.model.saltCore.validation;

import de.corpling.salt.model.saltCore.SFeatureDescription;
import de.corpling.salt.model.saltCore.SStereotype;
import de.corpling.salt.model.saltCore.SStereotypeContainer;

/**
 * A sample validator interface for {@link de.corpling.salt.model.saltCore.SStereotype}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SStereotypeValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSFeatureDescriptions(SFeatureDescription value);
	boolean validateSSuperStereotype(SStereotype value);
	boolean validateSProject(SStereotypeContainer value);
}
