<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="saltCore"
    nsURI="saltCore" nsPrefix="saltCore">
  <eClassifiers xsi:type="ecore:EClass" name="SNode" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//Node #//SAnnotatableElement #//SNamedElement #//SIdentifiableElement #//SProcessingAnnotatableElement #//SFeaturableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sGraph" eType="#//SGraph"
        volatile="true" transient="true" derived="true" eOpposite="#//SGraph/sNodes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SRelation" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//Edge #//SAnnotatableElement #//SNamedElement #//SIdentifiableElement #//SProcessingAnnotatableElement #//SFeaturableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sSource" eType="#//SNode"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sTarget" eType="#//SNode"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sGraph" eType="#//SGraph"
        volatile="true" transient="true" derived="true" eOpposite="#//SGraph/sRelations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SAnnotatableElement" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//LabelableElement">
    <eOperations name="addSAnnotation">
      <eParameters name="sAnnotation" eType="#//SAnnotation"/>
    </eOperations>
    <eOperations name="getSAnnotation" eType="#//SAnnotation">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sAnnotations" upperBound="-1"
        eType="#//SAnnotation" volatile="true" transient="true" derived="true" containment="true"
        eOpposite="#//SAnnotation/sAnnotatableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SAnnotation" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//Label">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sAnnotatableElement" eType="#//SAnnotatableElement"
        volatile="true" transient="true" eOpposite="#//SAnnotatableElement/sAnnotations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SGraph" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//Graph #//SNamedElement #//SAnnotatableElement #//SIdentifiableElement #//SProcessingAnnotatableElement #//SFeaturableElement">
    <eOperations name="addSNode">
      <eParameters name="sNode" eType="#//SNode"/>
    </eOperations>
    <eOperations name="getSNode" eType="#//SNode">
      <eParameters name="sNodeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addSRelation">
      <eParameters name="sRelation" eType="#//SRelation"/>
    </eOperations>
    <eOperations name="getSRelation" eType="#//SRelation">
      <eParameters name="sRelationId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sRelations" upperBound="-1"
        eType="#//SRelation" changeable="false" volatile="true" transient="true" derived="true"
        eOpposite="#//SRelation/sGraph"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sNodes" upperBound="-1"
        eType="#//SNode" changeable="false" volatile="true" transient="true" derived="true"
        eOpposite="#//SNode/sGraph"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SIdentifiableElement" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//IdentifiableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sElementId" eType="#//SElementId"
        volatile="true" transient="true" derived="true" eOpposite="#//SElementId/sIdentifiableElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sElementPath" eType="#//URI"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
  <eClassifiers xsi:type="ecore:EClass" name="SProcessingAnnotation" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//Label">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sProcessingAnnotatableElement"
        eType="#//SProcessingAnnotatableElement" volatile="true" transient="true"
        derived="true" eOpposite="#//SProcessingAnnotatableElement/sProcessingAnnotations"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SProcessingAnnotatableElement" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//LabelableElement">
    <eOperations name="addSProcessingAnnotation">
      <eParameters name="sProcessingAnnotation" eType="#//SProcessingAnnotation"/>
    </eOperations>
    <eOperations name="getSProcessingAnnotation" eType="#//SProcessingAnnotation">
      <eParameters name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sProcessingAnnotations"
        upperBound="-1" eType="#//SProcessingAnnotation" changeable="false" volatile="true"
        transient="true" derived="true" containment="true" eOpposite="#//SProcessingAnnotation/sProcessingAnnotatableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SElementId" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//Identifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sIdentifiableElement" eType="#//SIdentifiableElement"
        volatile="true" transient="true" derived="true" eOpposite="#//SIdentifiableElement/sElementId"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sElementPath" eType="#//URI"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SFeature" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//Label">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sFeaturableElement" eType="#//SFeaturableElement"
        volatile="true" transient="true" derived="true" eOpposite="#//SFeaturableElement/sFeatures"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SFeaturableElement" eSuperTypes="../../de.hub.corpling.Graph/model/graph.ecore#//LabelableElement">
    <eOperations name="addSFeature">
      <eParameters name="sFeature" eType="#//SFeature"/>
    </eOperations>
    <eOperations name="getSFeature" eType="#//SFeature">
      <eParameters name="sFeatureId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sFeatures" upperBound="-1"
        eType="#//SFeature" volatile="true" transient="true" derived="true" containment="true"
        eOpposite="#//SFeature/sFeaturableElement"/>
  </eClassifiers>
</ecore:EPackage>
