<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="saltCommon"
    nsURI="saltCommon" nsPrefix="saltCommon">
  <eClassifiers xsi:type="ecore:EClass" name="SaltProject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpusGraphs" upperBound="-1"
        eType="#//sCorpusStructure/SCorpusGraph" containment="true" eOpposite="#//sCorpusStructure/SCorpusGraph/saltProject"/>
  </eClassifiers>
  <eSubpackages name="sCorpusStructure" nsURI="sCorpusStructure" nsPrefix="sCorpusStructure">
    <eClassifiers xsi:type="ecore:EClass" name="SCorpusGraph" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SGraph">
      <eOperations name="getSCorpus" eType="#//sCorpusStructure/SCorpus">
        <eParameters name="sCorpusId" eType="ecore:EClass ../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SElementId"/>
      </eOperations>
      <eOperations name="getSDocument" eType="#//sCorpusStructure/SDocument">
        <eParameters name="sDocumentId" eType="ecore:EClass ../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SElementId"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocuments" upperBound="-1"
          eType="#//sCorpusStructure/SDocument" containment="true" eOpposite="#//sCorpusStructure/SDocument/sCorpusGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="saltProject" eType="#//SaltProject"
          eOpposite="#//SaltProject/sCorpusGraphs"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpora" upperBound="-1"
          eType="#//sCorpusStructure/SCorpus" containment="true" eOpposite="#//sCorpusStructure/SCorpus/sCorpusGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpusRelations" upperBound="-1"
          eType="#//sCorpusStructure/SCorpusRelation" containment="true" eOpposite="#//sCorpusStructure/SCorpusRelation/sCorpusGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpusDocumentRelations"
          upperBound="-1" eType="#//sCorpusStructure/SCorpusDocumentRelation" containment="true"
          eOpposite="#//sCorpusStructure/SCorpusDocumentRelation/sCorpusGraph"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SDocument" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpusGraph" eType="#//sCorpusStructure/SCorpusGraph"
          eOpposite="#//sCorpusStructure/SCorpusGraph/sDocuments"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocumentGraph" eType="#//sDocumentStructure/SDocumentGraph"
          eOpposite="#//sDocumentStructure/SDocumentGraph/sDocument"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SCorpus" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpusGraph" eType="#//sCorpusStructure/SCorpusGraph"
          eOpposite="#//sCorpusStructure/SCorpusGraph/sCorpora"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SCorpusRelation" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sSuperCorpus" eType="#//sCorpusStructure/SCorpus"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sSubCorpus" eType="#//sCorpusStructure/SCorpus"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpusGraph" eType="#//sCorpusStructure/SCorpusGraph"
          eOpposite="#//sCorpusStructure/SCorpusGraph/sCorpusRelations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SCorpusDocumentRelation" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpus" eType="#//sCorpusStructure/SCorpus"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocument" eType="#//sCorpusStructure/SDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sCorpusGraph" eType="#//sCorpusStructure/SCorpusGraph"
          eOpposite="#//sCorpusStructure/SCorpusGraph/sCorpusDocumentRelations"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="sDocumentStructure" nsURI="sDocumentStructure" nsPrefix="sDocumentStructure">
    <eClassifiers xsi:type="ecore:EClass" name="SDocumentGraph" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SGraph">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocument" eType="#//sCorpusStructure/SDocument"
          eOpposite="#//sCorpusStructure/SDocument/sDocumentGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sTextualDSs" upperBound="-1"
          eType="#//sDocumentStructure/STextualDS" volatile="true" transient="true"
          derived="true" containment="true" eOpposite="#//sDocumentStructure/STextualDS/sDocumentGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sTextualRelations" upperBound="-1"
          eType="#//sDocumentStructure/STextualRelation" volatile="true" transient="true"
          derived="true" containment="true" eOpposite="#//sDocumentStructure/STextualRelation/sDocumentGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sTokens" upperBound="-1"
          eType="#//sDocumentStructure/SToken" volatile="true" transient="true" derived="true"
          containment="true" eOpposite="#//sDocumentStructure/SToken/sDocumentGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sTimeline" eType="#//sDocumentStructure/STimeline"
          volatile="true" transient="true" derived="true" eOpposite="#//sDocumentStructure/STimeline/sDocumentGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sTimelineRelations" upperBound="-1"
          eType="#//sDocumentStructure/STimelineRelation" volatile="true" transient="true"
          derived="true" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sSpanningRelations" upperBound="-1"
          eType="#//sDocumentStructure/SSpanningRelation" volatile="true" transient="true"
          derived="true" containment="true" eOpposite="#//sDocumentStructure/SSpanningRelation/sDocumentGraph"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sSpans" upperBound="-1"
          eType="#//sDocumentStructure/SSpan" volatile="true" transient="true" derived="true"
          containment="true" eOpposite="#//sDocumentStructure/SSpan/sDocumentGraph"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="STextualDS" eSuperTypes="#//sDocumentStructure/SSequentialDS">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sText" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocumentGraph" eType="#//sDocumentStructure/SDocumentGraph"
          volatile="true" transient="true" derived="true" eOpposite="#//sDocumentStructure/SDocumentGraph/sTextualDSs"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SToken" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocumentGraph" eType="#//sDocumentStructure/SDocumentGraph"
          volatile="true" transient="true" derived="true" eOpposite="#//sDocumentStructure/SDocumentGraph/sTokens"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="STextualRelation" eSuperTypes="#//sDocumentStructure/SSequentialRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sToken" eType="#//sDocumentStructure/SToken"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sTextualDS" eType="#//sDocumentStructure/STextualDS"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocumentGraph" eType="#//sDocumentStructure/SDocumentGraph"
          volatile="true" transient="true" derived="true" eOpposite="#//sDocumentStructure/SDocumentGraph/sTextualRelations"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SSequentialRelation" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SRelation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sEnd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SSequentialDS" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SNode">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sData" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="STimeline" eSuperTypes="#//sDocumentStructure/SSequentialDS">
      <eOperations name="addSPointOfTime">
        <eParameters name="sPointOfTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sPointsOfTime" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocumentGraph" eType="#//sDocumentStructure/SDocumentGraph"
          volatile="true" transient="true" derived="true" eOpposite="#//sDocumentStructure/SDocumentGraph/sTimeline"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="STimelineRelation" eSuperTypes="#//sDocumentStructure/SSequentialRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sTimeline" eType="#//sDocumentStructure/STimeline"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sToken" eType="#//sDocumentStructure/SToken"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocumentGraph" eType="#//sDocumentStructure/SDocumentGraph"
          volatile="true" transient="true" derived="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SSpan" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SNode">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocumentGraph" eType="#//sDocumentStructure/SDocumentGraph"
          volatile="true" transient="true" derived="true" eOpposite="#//sDocumentStructure/SDocumentGraph/sSpans"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SSpanningRelation" eSuperTypes="../../de.hub.corpling.salt.SaltCore/model/saltCore.ecore#//SRelation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sToken" eType="#//sDocumentStructure/SToken"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sSpan" eType="#//sDocumentStructure/SSpan"
          volatile="true" transient="true" derived="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sDocumentGraph" eType="#//sDocumentStructure/SDocumentGraph"
          volatile="true" transient="true" eOpposite="#//sDocumentStructure/SDocumentGraph/sSpanningRelations"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
