/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.salt.model.salt.validation;

import de.corpling.salt.model.salt.SCorpus;
import de.corpling.salt.model.salt.SCorpusRelation;
import de.corpling.salt.model.salt.SDocument;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link de.corpling.salt.model.salt.SCorpusGraph}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SCorpusGraphValidator {
	boolean validate();

	boolean validateSCorpora(EList<SCorpus> value);
	boolean validateSDocuments(EList<SDocument> value);
	boolean validateSCorpusRelations(EList<SCorpusRelation> value);
}
