/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.salt.model.salt.validation;

import de.corpling.salt.model.salt.SCorpus;

/**
 * A sample validator interface for {@link de.corpling.salt.model.salt.SCorpusRelation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SCorpusRelationValidator {
	boolean validate();

	boolean validateSSuperCorpus(SCorpus value);

	boolean validateSSubCorpus(SCorpus value);

	boolean validateSuperCorpus(SCorpus value);
	boolean validateSubCorpus(SCorpus value);
}
