/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.salt.model.salt.validation;

import de.corpling.salt.model.salt.SCorpus;
import de.corpling.salt.model.salt.SDocument;

/**
 * A sample validator interface for {@link de.corpling.salt.model.salt.SCorpDocRelation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SCorpDocRelationValidator {
	boolean validate();

	boolean validateSCorpus(SCorpus value);

	boolean validateSDocument(SDocument value);

	boolean validateCorpus(SCorpus value);
	boolean validateDocument(SDocument value);
}
