/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.salt.model.salt.validation;

import de.corpling.salt.model.salt.SCorpusGraph;
import de.corpling.salt.model.salt.SDocumentGraph;


/**
 * A sample validator interface for {@link de.corpling.salt.model.salt.SDocument}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SDocumentValidator {
	boolean validate();

	boolean validateSDocumentGraph(SDocumentGraph value);

	boolean validateSCorpusGraph(SCorpusGraph value);

}
