/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package de.corpling.salt.model.salt.validation;

import de.corpling.salt.model.salt.SDocumentGraph;
import de.corpling.salt.model.salt.STextualDataSource;
import de.corpling.salt.model.salt.SToken;

/**
 * A sample validator interface for {@link de.corpling.salt.model.salt.STextualRelation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface STextualRelationValidator {
	boolean validate();

	boolean validateSToken(SToken value);
	boolean validateSTextualDataSource(STextualDataSource value);

	boolean validateSLeftPos(Long value);

	boolean validateSRightPos(Long value);

	boolean validateSDocumentGraph(SDocumentGraph value);
}
